/******************************************************************************
 *
 * Module: GPIO
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ultrasonic driver
 *
 * Author: Shirehan Medhat
 *
 *******************************************************************************/


/* For the delay functions */
#include <util/delay.h>
#include "../../STD_LIBRARIES/common_macros.h"
#include "../../MCAL/GPIO/gpio.h"
#include "../../MCAL/ICU/icu.h"
#include "ULTRASONIC.h"
uint8 COUNTER =0;
uint16 HIGH_TIME =0;
/*
 * • Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver.
• Inputs: None
• Return: None
 * */

void Ultrasonic_init(void)
{
	Icu_ConfigType INITIAL_ICU = {F_CPU_8 , RISING };
	/*1- initialize the ICU*/
	Icu_init(&INITIAL_ICU);
	/*2-Set Callback*/
	Icu_setCallBack (&Ultrasonic_edgeProcessing);
	/*3-Setup the direction for the trigger pin as output pin through the
	GPIO driver.*/
	GPIO_setupPinDirection (TRIGGER_PORT_ID , TRIGGER_PIN_ID , PIN_OUTPUT);
}
/*
 * void Ultrasonic_Trigger(void)
• Description
➢ Send the Trigger pulse to the ultrasonic.
• Inputs: None
• Return: None*/
void Ultrasonic_Trigger(void)
{
	/* Send the Trigger pulse to the ultrasonic.*/
	GPIO_writePin (TRIGGER_PORT_ID , TRIGGER_PIN_ID , LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin (TRIGGER_PORT_ID , TRIGGER_PIN_ID , LOGIC_LOW);

}
/*
 * uint16 Ultrasonic_readDistance(void)
• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
• Inputs: None
• Return: The measured distance in Centimeter*/

uint16 Ultrasonic_readDistance(void)
{
	uint16 DISTANCE =0;

	/*Send the trigger pulse by using Ultrasonic_Trigger function.*/
	Ultrasonic_Trigger ();
	    /*HIGH_TIME = (HIHG_TIME /2)*10POW(-6)   SEC
		 * DISITANCE = (HIGHTIME/2) * 10POW(-6) * 340   METER
		 * DISITANCE = (HIGHTIME/2) * 10POW(-6) * 340 * 10POW(2)  CM
		 *  DISITANCE = HIGHTIME * (.017) CM
		 *  But the Ultrasonic is not accurate so:
		 *  DISITANCE = HIGHTIME * (57.828125) CM
		 * */

	DISTANCE = (uint16)(( HIGH_TIME)/(CONVERSION_RATIO));

	return DISTANCE;
}

/*
 * void Ultrasonic_edgeProcessing(void)
• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
• Inputs: None
• Return: None*/
void Ultrasonic_edgeProcessing(void)
{
	COUNTER++;
	if (1== COUNTER)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType (FALLING);

	}
	else if (2== COUNTER)
	{
		HIGH_TIME = Icu_getInputCaptureValue ();
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType (RISING);
		COUNTER =0;

	}

}



